name: Tests

on:
    push:
        branches: [ master ]
    pull_request:
    release:
        types: [ created ]

jobs:
    composer-json:
        runs-on: ubuntu-latest
        name: Validate Composer configuration
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer
                    coverage: none

            -   name: Validate Composer configuration
                run: composer validate --strict

    unit-tests:
        runs-on: ubuntu-latest
        name: "Unit-Tests: ${{ matrix.php }} - PHAR readonly ${{ matrix.phar-readonly }}"
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1' ]
                phar-readonly: [ true, false ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: phar.readonly=0, display_errors=On, error_reporting=-1
                    tools: composer
                    coverage: none
                    extensions: ctype, iconv, xml

            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v1
                with:
                    composer-options: '--prefer-dist'

            -   name: Install Composer RequirementChecker dependencies
                uses: ramsey/composer-install@v1
                with:
                    working-directory: 'requirement-checker'
                    composer-options: '--prefer-dist'

            -   name: Validate Box configuration
                run: bin/box validate

            -   name: Run tests (PHAR readonly)
                if: matrix.phar-readonly == true
                run: make tu_box_phar_readonly

            -   name: Run tests (PHAR writeable)
                if: matrix.phar-readonly == false
                run: make tu

    coverage:
        runs-on: ubuntu-latest
        name: Coverage
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
                    ini-values: phar.readonly=0, display_errors=On, error_reporting=-1
                    tools: composer
                    coverage: pcov
                    extensions: ctype, iconv, xml

            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v1
                with:
                    composer-options: '--prefer-dist'

            -   name: Install Composer RequirementChecker dependencies
                uses: ramsey/composer-install@v1
                with:
                    working-directory: 'requirement-checker'
                    composer-options: '--prefer-dist'

            -   name: Run tests with coverage
                run: make tm

    e2e-tests:
        runs-on: ubuntu-latest
        name: "e2e-Tests: ${{ matrix.e2e }} - ${{ matrix.php }} - ${{ matrix.tools }}"
        strategy:
            fail-fast: false
            matrix:
                e2e:
                    - 'e2e_php_settings_checker'
                    - 'e2e_scoper_alias'
                    - 'e2e_scoper_whitelist'
                    - 'e2e_check_requirements'
                    - 'e2e_symfony'
                    - 'e2e_composer_installed_versions'
                php: [ '8.1' ]
        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: "phar.readonly=0, display_errors=On, error_reporting=-1"
                    tools: ${{ matrix.tools }}
                    coverage: pcov

            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v1
                with:
                    composer-options: '--prefer-dist'

            -   name: Install Composer RequirementChecker dependencies
                uses: ramsey/composer-install@v1
                with:
                    working-directory: 'requirement-checker'
                    composer-options: '--prefer-dist'

            -   name: Run end-to-end ${{ matrix.e2e }}
                run: make ${{ matrix.e2e }}
